import {ReactNode} from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
export default function RootLayout({
  children,
}: {
  children:ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}
      <div className="container-fluid bg-dark">
        <div className="row">
          <div className="col-12">
            <p className="text-danger text-white text-center">Fabiano Moraes ®</p>
          </div>
        </div>
      </div>
      </body>
    </html>
  )
}
